# Generated by Django 6.1 on 2026-08-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Поставщик')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('storage', models.CharField(max_length=20, verbose_name='Память')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name', 'storage', 'color'],
                'unique_together': {('name', 'storage', 'color')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15, unique=True, verbose_name='IMEI')),
                ('purchase_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Закупочная цена')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Цена продажи')),
                ('status', models.CharField(choices=[('IN_STOCK', 'В наличии'), ('SOLD', 'Продан')], default='IN_STOCK', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.product', verbose_name='Товар')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.purchase', verbose_name='Приход')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Цена продажи')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='api.sale', verbose_name='Продажа'),
        ),
    ]
