# Generated by Django 6.1 on 2026-08-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='extra_expenses',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Дополнительные расходы на устройство'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='extra_expenses',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Дополнительные расходы'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='extra_expenses_comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий к расходам'),
        ),
    ]
