# Generated by Django 6.1 on 2026-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device_extra_expenses_purchase_extra_expenses_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default='8 GB', max_length=20, verbose_name='Оперативная память'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'ram', 'storage', 'color')},
        ),
    ]
